import type { StaticImageData } from "next/image";

import odigosLogo from "@/public/images/partners/odigos.webp";
import oefeLogo from "@/public/images/partners/oefe.webp";

/**
 * Partner marks, generated by `scripts/prepare-partners.mjs`.
 *
 * Imported statically rather than referenced by path, so each file carries a
 * content hash and the image optimiser cannot serve stale bytes after a logo is
 * regenerated in place. The same reason the hero and the map are imported this
 * way.
 *
 * The keys match `logo` in `EXTERNAL_TOOLS`.
 */
export const PARTNER_LOGOS: Record<string, StaticImageData> = {
  oefe: oefeLogo,
  odigos: odigosLogo,
};
