/**
 * GENERATED by scripts/prepare-teachers.mjs. Do not edit by hand.
 *
 * Only teachers who sent a portrait appear here. The team section falls back
 * to the initial in a chalk frame for anyone missing.
 */
import type { GalleryImage } from "@/lib/general/gallery-blur";

export const TEAM_PHOTOS: Record<string, GalleryImage> = {
  "kallergi": {
    src: "/images/team/kallergi.webp",
    width: 900,
    height: 1125,
    blurDataURL:
      "data:image/jpeg;base64,/9j/2wBDABIMDRANCxIQDhAUExIVGywdGxgYGzYnKSAsQDlEQz85Pj1HUGZXR0thTT0+WXlaYWltcnNyRVV9hnxvhWZwcm7/2wBDARMUFBsXGzQdHTRuST5Jbm5ubm5ubm5ubm5ubm5ubm5ubm5ubm5ubm5ubm5ubm5ubm5ubm5ubm5ubm5ubm5ubm7/wAARCAAQAA0DASIAAhEBAxEB/8QAFQABAQAAAAAAAAAAAAAAAAAABgT/xAAhEAACAgEDBQEAAAAAAAAAAAACAwEEEQAFExIhUWFxMf/EABQBAQAAAAAAAAAAAAAAAAAAAAP/xAAWEQADAAAAAAAAAAAAAAAAAAAAAhH/2gAMAwEAAhEDEQA/AEe47wqg6Eys2s6OQhDGYHOM+/nrVymA9INUUEBjBDPmJ0DGw2xDb7Qa6yLONgj+ymR7TEfdI9q3KvVoKU4+HA5EDnuMeNBR2SH/2Q==",
  },
  "manthaiaki": {
    src: "/images/team/manthaiaki.webp",
    width: 900,
    height: 1125,
    blurDataURL:
      "data:image/jpeg;base64,/9j/2wBDABIMDRANCxIQDhAUExIVGywdGxgYGzYnKSAsQDlEQz85Pj1HUGZXR0thTT0+WXlaYWltcnNyRVV9hnxvhWZwcm7/2wBDARMUFBsXGzQdHTRuST5Jbm5ubm5ubm5ubm5ubm5ubm5ubm5ubm5ubm5ubm5ubm5ubm5ubm5ubm5ubm5ubm5ubm7/wAARCAAQAA0DASIAAhEBAxEB/8QAFQABAQAAAAAAAAAAAAAAAAAABAX/xAAjEAACAgEDAwUAAAAAAAAAAAABAgMRBAAFITFRYRQiQYGR/8QAFAEBAAAAAAAAAAAAAAAAAAAAA//EABYRAQEBAAAAAAAAAAAAAAAAAAEAAv/aAAwDAQACEQMRAD8Apb3uaxyejhkVZiGJDrYqifHb81IxJVbHWeAe6Xl1QcL2HTydL3TFZ82OSeNnEYJtSBxXzf1pe0YiQ4oqIAGgC18gdNEuZAb/2Q==",
  },
};
