/**
 * Turns the photos in `photos/` into the gallery assets.
 *
 *   node scripts/prepare-gallery.mjs
 *
 * For each photo it writes a WebP into `public/images/gallery/` and records the
 * intrinsic size plus a blurred placeholder into `lib/general/gallery-blur.ts`.
 *
 * The placeholder is the photo resized to 16px on its longest edge at JPEG
 * quality 45, inlined as a data URI. At that size it is a few hundred bytes of
 * colour, enough for the tile to show the right tones the moment the page paints
 * instead of a hole that fills in later. The intrinsic size travels with it so
 * neither the masonry tile nor the lightbox shifts once the real file arrives.
 *
 * The map lives in its own generated file rather than in the business constants,
 * because base64 placeholders are kilobytes of noise that no one should have to
 * scroll past to find a phone number.
 */
import { writeFile } from "node:fs/promises";
import path from "node:path";

import sharp from "sharp";

const SOURCE_DIR = "photos";
const OUT_DIR = "public/images/gallery";
const MAP_FILE = "lib/general/gallery-blur.ts";
const MAX_EDGE = 1600;
const BLUR_EDGE = 16;

/**
 * Explicit filename to slug, not "sort the folder and zip". `photos/` also holds
 * the teacher portraits and the roll-up scan, and a positional mapping silently
 * reassigns every caption the moment anything else lands in there.
 */
const SOURCES = [
  { file: "εικόνα_Viber_2026-07-28_15-20-07-649.jpg", slug: "cards" },
  { file: "εικόνα_Viber_2026-07-28_15-20-07-747.jpg", slug: "reception-desk" },
  { file: "εικόνα_Viber_2026-07-28_15-20-07-961.jpg", slug: "reception-corner" },
  { file: "εικόνα_Viber_2026-07-28_15-20-09-846.jpg", slug: "classroom" },
  { file: "εικόνα_Viber_2026-07-28_15-20-09-965.jpg", slug: "study-room" },
  { file: "εικόνα_Viber_2026-07-28_15-20-15-794.jpg", slug: "waiting-area" },
  { file: "εικόνα_Viber_2026-07-28_15-20-22-069.jpg", slug: "office" },
];

const toDataUri = async (input) => {
  const buffer = await sharp(input)
    .rotate()
    .resize({ width: BLUR_EDGE, height: BLUR_EDGE, fit: "inside" })
    .jpeg({ quality: 45 })
    .toBuffer();

  return `data:image/jpeg;base64,${buffer.toString("base64")}`;
};

const run = async () => {
  const entries = [];

  for (const { file, slug } of SOURCES) {
    const source = path.join(SOURCE_DIR, file);
    const target = path.join(OUT_DIR, `${slug}.webp`);

    await sharp(source)
      .rotate()
      .resize({ width: MAX_EDGE, height: MAX_EDGE, fit: "inside", withoutEnlargement: true })
      .webp({ quality: 80 })
      .toFile(target);

    const { width, height } = await sharp(target).metadata();
    const blurDataURL = await toDataUri(source);

    entries.push({ slug, width, height, blurDataURL });
    console.log(`${file} -> ${slug}.webp ${width}x${height}, blur ${blurDataURL.length}b`);
  }

  const body = entries
    .map(
      (entry) =>
        `  "${entry.slug}": {\n` +
        `    src: "/images/gallery/${entry.slug}.webp",\n` +
        `    width: ${entry.width},\n` +
        `    height: ${entry.height},\n` +
        `    blurDataURL:\n      "${entry.blurDataURL}",\n` +
        `  },`,
    )
    .join("\n");

  const contents =
    `/**\n` +
    ` * GENERATED by scripts/prepare-gallery.mjs. Do not edit by hand.\n` +
    ` *\n` +
    ` * Each entry carries the served file, its intrinsic size so nothing shifts as\n` +
    ` * it loads, and a 16px blurred placeholder inlined as a data URI.\n` +
    ` */\n` +
    `export interface GalleryImage {\n` +
    `  src: string;\n` +
    `  width: number;\n` +
    `  height: number;\n` +
    `  blurDataURL: string;\n` +
    `}\n\n` +
    `export const GALLERY_IMAGES: Record<string, GalleryImage> = {\n${body}\n};\n`;

  await writeFile(MAP_FILE, contents, "utf8");
  console.log(`\nWrote ${MAP_FILE} with ${entries.length} entries`);
};

run().catch((error) => {
  console.error(error.message);
  process.exit(1);
});
